# Generated by Django 5.1.1 on 2024-11-28 20:31

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="token",
            field=models.UUIDField(
                default=uuid.UUID("f48acc19-5a84-426c-8f4f-1bc66fa6a75f")
            ),
        ),
    ]
